#!/usr/bin/ruby
kernel = `uname -r`
puts "\e[1mkernel\e[0m "+kernel
shell = `echo $SHELL`.gsub("/usr", "").gsub("/bin/", "")
puts "\e[1mshell\e[0m "+shell
distro = `cat /etc/os-release | head -n 1`.gsub("PRETTY_NAME=", "").gsub("\"", "")
puts "\e[1mdistro\e[0m "+distro
if distro.include?("Rhino")
  puts "\e[1m\e[35m       .;:;,.  .:       "
  puts "\e[1m\e[35m    'coooooooo:oo.';.   "
  puts "\e[1m\e[35m  ,oooooooooooooooo    ;"
  puts "\e[1m\e[35m clllcccllloooooooo;c:'o"
  puts "\e[1m\e[35m.;';:::::::::cclooooooo'"
  puts "\e[1m\e[35m''',::::::::::::::ccclc."
  puts "\e[1m\e[35m.''';::::::::::\e[36ml\e[35m::::::: "
  puts "\e[1m\e[35m '''',:::::::::\e[36kd\e[35m.      "
  puts "\e[1m\e[35m .''''',;::\e[36mck:oW\e[35m;       "
  puts "\e[1m\e[35m   ''''''''\e[36mkXOM.        "
  puts "\e[1m\e[35m     .,,:\e[36mdXMK           "
  puts "\e[1m\e[36m       :k               "
elsif distro.include?("Arch")
  
