#!/usr/bin/ruby
logos = "./logos/"
kernel = `uname -r`
puts "\e[1mkernel\e[0m "+kernel
shell = `echo $SHELL`.gsub("/usr", "").gsub("/bin/", "")
puts "\e[1mshell\e[0m "+shell
distro = `cat /etc/os-release | head -n 1`.gsub("PRETTY_NAME=", "").gsub("\"", "")
puts "\e[1mdistro\e[0m "+distro
if distro.include?("Rhino")
ascii = `cat #{logos}Rhino`
puts ascii
end  
